version: "3"

dotenv: [".env"]
silent: true

tasks:
  app:
    - turbo run dev --scope="launchpad-webapp"

  faucet:
    - turbo run dev --scope="launchpad-faucet"

  indexer:
    - turbo run dev --scope="launchpad-indexer"
