version: "3"

dotenv: [".env"]
silent: true

tasks:
  app:
    - turbo run dev --scope="smartsale-webapp"

  faucet:
    - turbo run dev --scope="smartsale-faucet"

  indexer:
    - turbo run dev --scope="smartsale-indexer"
