
name: Subgraph CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
jobs:
  echo:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: echo
        run: echo 'Migrations disabled'

# name: Release

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:
#   release:
#     runs-on: ubuntu-latest

#     env:
#       SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
#       SUPABASE_DB_PASSWORD: ${{ secrets.PRODUCTION_DB_PASSWORD }}
#       SUPABASE_PROJECT_ID: ${{ secrets.PRODUCTION_PROJECT_ID }}

#     steps:
#       - uses: actions/checkout@v3

#       - uses: supabase/setup-cli@v1
#         with:
#           version: latest

#       - name: Link Supabase Project
#         run: supabase link --project-ref $SUPABASE_PROJECT_ID
#         working-directory: ./apps/supabase

#       - name: Push Database Changes
#         run: supabase db push
#         working-directory: ./apps/supabase
